flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/posts/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title = 'New post', form=form)

@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)
    
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title = 'Update post', form=form)
    
@posts.route('/post/<int:post_id>/delete', methods=['GET'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint, request, flash, url_for, render_template, redirect
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.models import User, Post
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f'Congratulations!!! Account created for {form.username.data}!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registration form', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login unsuccessful. Please check the email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/'+current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template('user_posts.html', posts=posts, user=user)

@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instruction to reset the password')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid token')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Password updated')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset password', form=form)

flaskblog/templates/about.html
{% extends "layout.html" %}

{% block content %}
<h1>About us</h1>
{% endblock content %}

flaskblog/templates/account.html
{% extends "layout.html" %}

{% block content %}
<div>
    <div>
        <img src="{{ image_file }}" alt="profile image">
        <div>
            <h2>{{ current_user.username }}</h2>
            <p>{{ current_user.email }}</p>
        </div>
    </div>
</div>
<div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Account Info</legend>
            <div>
                {{ form.username.label }}
                {% if form.username.errors %}
                {{ form.username }}
                <div>
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username }}
                {% endif %}
            </div>
            <div>
                {{ form.email.label }}
                {% if form.email.errors %}
                {{ form.email }}
                <div>
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email }}
                {% endif %}
            </div>
            <div>
                {{ form.picture.label }}
                {{ form.picture }}
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span>{{ error }}</span><br>
                {% endfor %}
                {% endif %}
            </div>
        </fieldset>
        <div>
            {{ form.submit }}
        </div>
    </form>
</div>
</div>

{% endblock content %}

flaskblog/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>New Post</legend>
            <div>
                {{ form.title.label }}
                {% if form.title.errors %}
                {{ form.title }}
                <div>
                    {% for error in form.title.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.title }}
                {% endif %}
            </div>
            <div>
                {{ form.content.label }}
                {% if form.content.errors %}
                {{ form.content }}
                <div>
                    {% for error in form.content.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.content }}
                {% endif %}
            </div>

        </fieldset>
        <div>
            {{ form.submit }}
        </div>
    </form>
</div>
{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}

{% block content %}
<h1>Home page</h1>
<br>
<hr>
<hr>
<hr>
{% for post in posts.items %}
<img src="{{url_for('static', filename='profile_pics/'+post.author.image_file)}}" alt="profile pic">
<h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
<h3>{{ post.content }}</h3>
<a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
<small>{{ post.date_posted.strftime('%y-%m-%d') }}</small>
<hr>
{% endfor %}

{% for page_no in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_no %}
{% if posts.page == page_no %}
<a href="{{ url_for('main.home', page=page_no) }}">{{ page_no }}</a>
{% else %}
<a href="{{ url_for('main.home', page=page_no) }}">{{ page_no }}</a>
{% endif %}
{% else %}

{% endif %}

{% endfor %}

{% endblock content %}

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>Flask Blog - {{ title }}</title>
    {% else %}
    <title>FlaskBlog</title>
    {% endif %}
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
</body>

</html>

flaskblog/templates/login.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Login</legend>
            <div>
                {{ form.email.label }}
                {% if form.email.errors %}
                {{ form.email }}
                <div>
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email }}
                {% endif %}
            </div>
            <div>
                {{ form.password.label }}
                {% if form.password.errors %}
                {{ form.password }}
                <div>
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password }}
                {% endif %}
            </div>
            <div>
                {{ form.remember }}
                {{ form.remember.label }}
            </div>
        </fieldset>
        <div>
            {{ form.submit }}
        </div>
        <small><a href="{{ url_for('users.reset_request')}}">Forgot Password?</a></small>
    </form>
</div>
<div>
    <small>
        Need an account? <a href="{{ url_for('users.register') }}">Sign Up Now</a>
    </small>
</div>
{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}

{% block content %}
<div>
    <h1>Post</h1>
    <br>
    <hr>
    <hr>
    <hr>

    <img src="{{url_for('static', filename='profile_pics/'+post.author.image_file)}}" alt="profile pic">
    <h2>{{ post.title }}</h2>
    <h3>{{ post.content }}</h3>
    <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
    <small>{{ post.date_posted.strftime('%y-%m-%d') }}</small>
    <br>
    {% if post.author == current_user %}
    <a href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
    <a href="{{ url_for('posts.delete_post', post_id=post.id) }}">Delete</a>

    {% endif %}
    <hr>
</div>
{% endblock content %}

flaskblog/templates/register.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Join Today</legend>
            <div>
                {{ form.username.label }}
                {% if form.username.errors %}
                {{ form.username }}
                <div>
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.username }}
                {% endif %}
            </div>
            <div>
                {{ form.email.label }}
                {% if form.email.errors %}
                {{ form.email }}
                <div>
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email }}
                {% endif %}
            </div>
            <div>
                {{ form.password.label }}
                {% if form.password.errors %}
                {{ form.password }}
                <div>
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password }}
                {% endif %}
            </div>
            <div>
                {{ form.confirm_password.label }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password }}
                <div>
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password }}
                {% endif %}
            </div>
        </fieldset>
        <div>
            {{ form.submit }}
        </div>
    </form>
</div>
<div>
    <small>
        Already have an account? <a href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock content %}

flaskblog/templates/reset_request.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Reset Password</legend>
            <div>
                {{ form.email.label }}
                {% if form.email.errors %}
                {{ form.email }}
                <div>
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.email }}
                {% endif %}
            </div>

        </fieldset>
        <div>
            {{ form.submit }}
        </div>

    </form>
</div>
{% endblock content %}

flaskblog/templates/reset_token.html
{% extends "layout.html" %}

{% block content %}
<div>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset>
            <legend>Reset Password</legend>
            <div>
                {{ form.password.label }}
                {% if form.password.errors %}
                {{ form.password }}
                <div>
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.password }}
                {% endif %}
            </div>

            <div>
                {{ form.confirm_password.label }}
                {% if form.confirm_password.errors %}
                {{ form.confirm_password }}
                <div>
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% else %}
                {{ form.confirm_password }}
                {% endif %}
            </div>

        </fieldset>
        <div>
            {{ form.submit }}
        </div>

    </form>
</div>
{% endblock content %}

flaskblog/templates/user_posts.html
{% extends "layout.html" %}

{% block content %}
<div>
    <h1>Posts by {{ user.username }} ({{ posts.total }})</h1>
    <br>
    <hr>
    <hr>
    <hr>
    {% for post in posts.items %}
    <img src="{{url_for('static', filename='profile_pics/'+post.author.image_file)}}" alt="profile pic">
    <h2><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <h3>{{ post.content }}</h3>
    <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
    <small>{{ post.date_posted.strftime('%y-%m-%d') }}</small>
    <hr>
    {% endfor %}

    {% for page_no in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_no %}
    {% if posts.page == page_no %}
    <a href="{{ url_for('users.user_posts', username=user.username, page=page_no) }}">{{ page_no }}</a>
    {% else %}
    <a href="{{ url_for('users.user_posts', username=user.username, page=page_no) }}">{{ page_no }}</a>
    {% endif %}
    {% else %}

    {% endif %}

    {% endfor %}
</div>
{% endblock content %}